# Generated by Django 5.2.8 on 2025-11-29 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browserapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cv/')),
                ('contrat', models.JSONField(blank=True, default=list)),
                ('location', models.JSONField(blank=True, default=list)),
                ('pays', models.JSONField(blank=True, default=list)),
                ('duree', models.PositiveIntegerField(blank=True, null=True)),
                ('langue', models.JSONField(blank=True, default=list)),
                ('domaine', models.JSONField(blank=True, default=list)),
                ('anotherinfo', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
